source 'https://rubygems.org'
gem 'chefspec',   '~> 4.0'
gem 'foodcritic', '~> 4.0'
gem 'rubocop',    '~> 1.50'

group :integration do
  gem 'test-kitchen',    '~> 1.0'
  gem 'kitchen-vagrant', '~> 0.11'
end
