name             'centos7'
maintainer       'hiroyasu55(LogicHeart)'
maintainer_email 'hiroyasu.yamada@logicheart.biz'
license          'All rights reserved'
description      'Initialize Linux(CentOS 7) environment on VirtuakBox'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.0'
depends          'yum-epel'
depends          'selinux'
depends          'iptables'
depends          'clamav', '~> 1.3.0'
depends          'ntp'
